# Generated by Django 3.2.6 on 2021-08-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('escolaridad', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('contrato', models.CharField(max_length=2)),
                ('vulnerabilidad', models.CharField(max_length=200)),
                ('proyectable', models.CharField(max_length=2)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
